# Generated by Django 6.0 on 2026-02-17 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('provider', models.CharField(choices=[('NETFLIX', 'Netflix'), ('PRIME', 'Amazon Prime Video'), ('APPLE', 'Apple TV+')], max_length=20)),
                ('poster_path', models.CharField(blank=True, default='', max_length=255)),
                ('vote_average', models.FloatField(blank=True, null=True)),
                ('overview', models.TextField(blank=True, default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
