# Generated by Django 6.0 on 2026-02-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_watchlistitem_user_alter_watchlistitem_provider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlistitem',
            name='provider',
            field=models.CharField(choices=[('NETFLIX', 'Netflix'), ('PRIME', 'Amazon Prime'), ('APPLE', 'Apple TV')], max_length=20),
        ),
    ]
